---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: pe0
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: node1
  virtualRouters:
  # Peer with XR and advertise Pod CIDR
  - localASN: 65000
    exportPodCIDR: true
    mapSRv6VRFs: true
    neighbors:
    - peerAddress: "10.12.10.1/32"
      peerASN: 66000

      