---
apiVersion: cilium.io/v2alpha1
kind: CiliumSRv6VRF
metadata:
  name: vrf0
spec:
  vrfID: 1
  importRouteTarget: "65000:1"
  exportRouteTarget: "65000:1"
  rules:
  - selectors:
    - podSelector:
        matchLabels:
          vrf: vrf0
    destinationCIDRs:
    - 10.3.0.0/24